### ISSUE TITLE
Symbol's value as variable is void: lldot

### ISSUE THREAD

**Issue by smaret** [cdominik/mu2tex#1]
Thanks Carsten for this package.

 In Emacs 26.1 on macos 10.14.4, I get the following error when expanding `H2O` or `C18O`:

```
and: Symbol’s value as variable is void: lldot
```

How can this be fixed?

**Comment by cdominik** [comment]
Hi Sébastien,

nice to hear from you!  Hope you are well?

Thank you for the report, no idea how that got in there.  Fixed now.  Let
me know if it is useful and if you have ideas for improvements.

Carsten

**Comment by smaret** [comment]
Thanks for the fix!

For the record: this is fixed with 8e5c10209e540dfe542ad
